### ISSUE TITLE
Let BehaviorSubject.imapSubject return a BehaviorSubject

### ISSUE THREAD

**Issue by fdietze** [cornerman/colibri#193]

**Comment by cornerman** [comment]
True, but will need a bit of boilerplate code that we have to write here. But can be okay. Is it in order to keep the `now()` method?

**Comment by cornerman** [comment]
You can do this now with [colibri-reactive](https://github.com/cornerman/colibri/blob/master/reactive/src/main/scala/colibri/reactive/Reactive.scala#L109), if it helps.

**Comment by cornerman** [comment]
Generally, I am thinking of removing the `now` method in most parts of the core `Observable` API. They just do not make too much sense for lazy observables. It only works for subjects and things that you create from subjects directly. But we have to handle no intiial value, maybe initial value and always initial value.

I feel like the `now` methods is better for hot obseravbles which is what we now have in `outwatch-reactive`.

**Comment by fdietze** [comment]
> True, but will need a bit of boilerplate code that we have to write here. But can be okay. Is it in order to keep the `now()` method?

Yes, keeping the `now()` method is the motivation.

**Comment by cornerman** [comment]
Can we close this? I hope, we can provide the desired interface in the reactive project.
