### ISSUE TITLE
Allow observable.subscribe(var) when Owner available

### ISSUE THREAD

**Issue by fdietze** [cornerman/colibri#213]
I'd like to sync `Observable` into `RxWriter`/`Observers`:

```scala
// with implicit Owner in scope:
val number = Var(0)
Observable.intervalMillis(1000).subscribe(number)
```

**Comment by cornerman** [comment]
Just to understand better: You mean, that subscribe on observables should take an implicit owner? I would not like to do that, I think the owner concept is good for the hot variables use-case, but not generally for observables.

You can easily just convert the observable to an `Rx` and work from there:
```
Rx.observableSync(Observable.intervalMillis(1000)).subscribe(number)
```

**Comment by cornerman** [comment]
closed via https://github.com/cornerman/colibri/pull/271
